language: node_js
node_js:
    - "0.10"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install # data-system
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - ps aux | grep server.js
    - sleep 15
    - cat forever-ds.log
    - sudo netstat -plunt
    - curl http://localhost:9101/
    - coffee commands.coffee test-install test ../tests/server/allpermissions.json
    - cd ..
    - export NAME=test
    - export TOKEN=apptoken