// Generated by CoffeeScript 1.9.1
(function() {
  var DS_PORT, client, ref, request;

  request = require('request-json-light');

  DS_PORT = process.env.DS_PORT || 9101;

  client = request.newClient("http://localhost:" + DS_PORT);

  if ((ref = process.env.NODE_ENV) === "production" || ref === "test") {
    client.setBasicAuth(process.env.NAME, process.env.TOKEN);
  } else {
    client.setBasicAuth(Math.random().toString(36), "token");
  }

  module.exports = client;

}).call(this);
